//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cizgi_School_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Number { get; set; }
        public string PhoneNumber { get; set; }
        public string Mail { get; set; }
        public string Image { get; set; }
    }
}
